// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: cpf, secret
func (_m *Service) SignIn(cpf string, secret string) (string, error) {
	ret := _m.Called(cpf, secret)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(cpf, secret)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(cpf, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
