definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: status bad request
        type: string
      message:
        example: status bad request
        type: string
    type: object
  representation.AccountCreated:
    properties:
      balance:
        type: number
      cpf:
        type: string
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  representation.NewAccount:
    properties:
      balance:
        type: number
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    required:
    - cpf
    - name
    - secret
    type: object
info:
  contact:
    email: evandroferreiras@gmail.com
    name: Evandro Souza
  license: {}
  title: Gopher City Bank API
  version: "1.0"
paths:
  /api/accounts:
    post:
      consumes:
      - application/json
      description: Creates a new account
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/representation.NewAccount'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/representation.AccountCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create account
      tags:
      - accounts
  /api/healthcheck:
    get:
      description: Returns true or false, depeding on the state of app.
      responses:
        "200":
          description: WORKING
          schema:
            type: integer
        "400":
          description: NOT WORKING
          schema:
            type: integer
      summary: IsOnline
swagger: "2.0"
