definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: status bad request
        type: string
      message:
        example: status bad request
        type: string
    type: object
  representation.AccountBalanceResponse:
    properties:
      balance:
        type: number
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  representation.AccountResponse:
    properties:
      cpf:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  representation.AccountsList:
    properties:
      accounts:
        items:
          $ref: '#/definitions/representation.AccountResponse'
        type: array
      count:
        type: integer
    type: object
  representation.LoginBody:
    properties:
      cpf:
        type: string
      secret:
        type: string
    required:
    - cpf
    - secret
    type: object
  representation.LoginResponse:
    properties:
      token:
        type: string
    type: object
  representation.NewAccountBody:
    properties:
      balance:
        type: number
      cpf:
        type: string
      name:
        type: string
      secret:
        type: string
    required:
    - cpf
    - name
    - secret
    type: object
  representation.TransferBody:
    properties:
      account_destination_id:
        type: string
      amount:
        type: number
    required:
    - account_destination_id
    - amount
    type: object
  representation.TransferDepositResponse:
    properties:
      account_origin_id:
        type: string
      amount:
        type: number
      date:
        type: string
    type: object
  representation.TransferListResponse:
    properties:
      deposits:
        items:
          $ref: '#/definitions/representation.TransferDepositResponse'
        type: array
      withdraws:
        items:
          $ref: '#/definitions/representation.TransferWithDrawResponse'
        type: array
    type: object
  representation.TransferWithDrawResponse:
    properties:
      account_destination_id:
        type: string
      amount:
        type: number
      date:
        type: string
    type: object
info:
  contact:
    email: evandroferreiras@gmail.com
    name: Evandro Souza
  license: {}
  title: Gopher City Bank API
  version: "1.0"
paths:
  /api/accounts:
    get:
      consumes:
      - application/json
      parameters:
      - description: page to return
        in: query
        name: page
        type: integer
      - description: page size to return
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/representation.AccountsList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get all accounts
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Creates a new account
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/representation.NewAccountBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/representation.AccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create account
      tags:
      - accounts
  /api/accounts/{account_id}/balance:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID of the account to get
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/representation.AccountBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get account balance information
      tags:
      - accounts
  /api/healthcheck:
    get:
      description: Returns true or false, depeding on the state of app.
      responses:
        "200":
          description: WORKING
          schema:
            type: integer
        "400":
          description: NOT WORKING
          schema:
            type: integer
      summary: IsOnline
  /api/login:
    post:
      consumes:
      - application/json
      description: SignIn for existing user
      parameters:
      - description: Credentials to use
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/representation.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/representation.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: SignIn for existing user
      tags:
      - login
  /api/transfers:
    get:
      description: List all transfers of an account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/representation.TransferListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: List all transfers of an account
      tags:
      - transfer
    post:
      consumes:
      - application/json
      description: Transfer money to another account
      parameters:
      - description: account destination and amount
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/representation.TransferBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/representation.AccountBalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: Transfer money to another account
      tags:
      - transfer
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
